# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OracleToolsMainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnectionDataBase = QtWidgets.QAction(MainWindow)
        self.actionConnectionDataBase.setObjectName("actionConnectionDataBase")
        self.actionLog_Off = QtWidgets.QAction(MainWindow)
        self.actionLog_Off.setObjectName("actionLog_Off")
        self.actionTnsnames_ora = QtWidgets.QAction(MainWindow)
        self.actionTnsnames_ora.setObjectName("actionTnsnames_ora")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAWR_Report = QtWidgets.QAction(MainWindow)
        self.actionAWR_Report.setObjectName("actionAWR_Report")
        self.actionASH_Report = QtWidgets.QAction(MainWindow)
        self.actionASH_Report.setObjectName("actionASH_Report")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.actionUser_s_Guide = QtWidgets.QAction(MainWindow)
        self.actionUser_s_Guide.setObjectName("actionUser_s_Guide")
        self.actionIssue_Feedback = QtWidgets.QAction(MainWindow)
        self.actionIssue_Feedback.setObjectName("actionIssue_Feedback")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionView_Tablespace = QtWidgets.QAction(MainWindow)
        self.actionView_Tablespace.setObjectName("actionView_Tablespace")
        self.menu.addAction(self.actionConnectionDataBase)
        self.menu.addAction(self.actionLog_Off)
        self.menu.addSeparator()
        self.menu.addAction(self.actionTnsnames_ora)
        self.menu.addSeparator()
        self.menu.addAction(self.actionSetting)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menuReport.addAction(self.actionAWR_Report)
        self.menuReport.addAction(self.actionASH_Report)
        self.menuSetting.addAction(self.actionView_Tablespace)
        self.menuAbout.addAction(self.actionUser_s_Guide)
        self.menuAbout.addAction(self.actionIssue_Feedback)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OracleTools"))
        self.menu.setTitle(_translate("MainWindow", "Connection"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.menuSetting.setTitle(_translate("MainWindow", "Tools"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionConnectionDataBase.setText(_translate("MainWindow", "Sign on"))
        self.actionLog_Off.setText(_translate("MainWindow", "Sign out"))
        self.actionTnsnames_ora.setText(_translate("MainWindow", "Open tnsnames.ora"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAWR_Report.setText(_translate("MainWindow", "AWR Report"))
        self.actionASH_Report.setText(_translate("MainWindow", "ASH Report"))
        self.actionSetting.setText(_translate("MainWindow", "Setting"))
        self.actionUser_s_Guide.setText(_translate("MainWindow", "User\'s Guide"))
        self.actionIssue_Feedback.setText(_translate("MainWindow", "Help Center"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionView_Tablespace.setText(_translate("MainWindow", "View Tablespace"))

